package net.lesscoding.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import net.lesscoding.common.BaseEntity;
import org.springframework.format.annotation.DateTimeFormat;

import java.time.LocalDateTime;

/**
 * @author eleven
 * @date 2022-11-10 19:55:27
 * @description tb_operation_log 操作日志表实体类
 * Generated By: lesscoding.net basic service
 * Link to: <a href="https://lesscoding.net">https://lesscoding.net</a>
 * mail to:2496290990@qq.com zjh292411@gmail.com admin@lesscoding.net
 */
@Data
@TableName("tb_operation_log")
public class OperationLog extends BaseEntity<OperationLog> {

    //@ApiModelProperty(" 操作模块")
    private String title;

    //@ApiModelProperty(" 业务类型")
    private Integer businessType;

    //@ApiModelProperty(" 请求方法")
    private String method;

    //@ApiModelProperty(" 方法耗时")
    private Long methodIntervalMs;

    //@ApiModelProperty(" 请求类型 get post delete put")
    private String requestMethod;

    //@ApiModelProperty(" 操作类别(0其它 1后台用户 2手机端用户 3手持端pda用户 4app用户)")
    private Integer operatorType;

    //@ApiModelProperty(" 操作人员")
    private String operName;

    //@ApiModelProperty(" 服务器ip地址")
    private String serverIp;

    //@ApiModelProperty(" 服务端口号")
    private String serverPort;

    //@ApiModelProperty(" 请求url")
    private String operUrl;

    //@ApiModelProperty(" 操作者ip")
    private String operIp;

    //@ApiModelProperty(" 操作ip地址")
    private String operLocation;

    //@ApiModelProperty(" 接口参数")
    private String operParam;

    //@ApiModelProperty(" 接口返回参数")
    private String jsonResult;

    //@ApiModelProperty(" 接口状态 0正常 1异常")
    private Integer status;

    //@ApiModelProperty(" 错误信息")
    private String errorMsg;

    //@ApiModelProperty(" 操作时间")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "Asia/ShangHai")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime operTime;

    //@ApiModelProperty("设备型号")
    private String userAgent;

}