//package net.lesscoding.config;
//
//import org.springframework.context.annotation.Bean;
//import org.springframework.context.annotation.Configuration;
//import springfox.documentation.builders.ApiInfoBuilder;
//import springfox.documentation.builders.PathSelectors;
//import springfox.documentation.builders.RequestHandlerSelectors;
//import springfox.documentation.service.Contact;
//import springfox.documentation.spi.DocumentationType;
//import springfox.documentation.spring.web.plugins.Docket;
//
///**
// * @author eleven
// * @date  2022-11-10 19:55:27
// * @description Knife配置类，用于生成swagger文档，Knife是swagger的一个UI库
// * Generated By: lesscoding.net basic service
// * Link to: <a href="https://lesscoding.net">https://lesscoding.net</a>
// * mail to:2496290990@qq.com zjh292411@gmail.com admin@lesscoding.net
// */
//@Configuration
//public class KnifeConfig {
//
//    @Bean
//    public Docket docket(){
//        return new Docket(DocumentationType.OAS_30)
//                .apiInfo(new ApiInfoBuilder()
//                        .description("# SysCompany Restful APIs")
//                        .termsOfServiceUrl("http://lesscoding.net")
//                        .contact(new Contact("eleven","http://lesscoding.net","2496290990@qq.com"))
//                        .version("1.0")
//                        .build())
//                //分组名称
//                .groupName("1.0.0版本")
//                .select()
//                //这里指定Controller扫描包路径
//                .apis(RequestHandlerSelectors.basePackage("net.lesscoding.controller"))
//                .paths(PathSelectors.any())
//                .build();
//    }
//
//}
