package net.lesscoding.service;

import com.baomidou.mybatisplus.extension.service.IService;
import net.lesscoding.common.Result;
import net.lesscoding.entity.OperationLog;

import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * @author eleven
 * @date 2022-11-10 19:55:27
 * @description tb_operation_log 操作日志表实体类
 * Generated By: lesscoding.net basic service
 * Link to: <a href="https://lesscoding.net">https://lesscoding.net</a>
 * mail to:2496290990@qq.com zjh292411@gmail.com admin@lesscoding.net
 */
public interface OperationLogService extends IService<OperationLog> {
    /**
     * 根据条件分页查询表格结果
     *
     * @return Result
     */
    public Result getPageByLike(OperationLog OperationLog);

}