
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间
    timeout: 10s
  application:
    name: ikun_dld
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    password: dream
    url: jdbc:mysql:///xedld?serverTimezone=UTC
    username: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: net.lesscoding.entity
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 9527
