package net.lesscoding.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import net.lesscoding.entity.OperationLog;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @author eleven
 * @date 2022-11-10 19:55:27
 * @description tb_operation_log 操作日志表 Mapper接口
 * Generated By: lesscoding.net basic service
 * Link to: <a href="https://lesscoding.net">https://lesscoding.net</a>
 * mail to:2496290990@qq.com zjh292411@gmail.com admin@lesscoding.net
 */
public interface OperationLogMapper extends BaseMapper<OperationLog> {

    List<OperationLog> getPageByLike(OperationLog OperationLog);

    OperationLog getOperationLogById(Integer id);

    int insertBatch(@Param("list") List<OperationLog> list);

}
