package net.lesscoding.common;


/**
 * @author eleven
 * @date  2022-11-10 19:55:27
 * @description 系统常量类
 * Generated By: lesscoding.net basic service
 * Link to: <a href="https://lesscoding.net">https://lesscoding.net</a>
 * mail to:2496290990@qq.com zjh292411@gmail.com admin@lesscoding.net
 */
public class Consts {
    /** 成功标识 */
    public static final Integer SUCCESS_CODE = 200;
    /** 失败标识 */
    public static final Integer FAILED_CODE = 500;
    /** 成功返回信息 */
    public static final String SUCCESS_MSG = "success";
    /** 失败返回信息 */
    public static final String FAILED_MSG = "failed";
    /**
     * 能量key
     */
    public static final String ENERGY_KEYS = "energy:*";

    /** 生成密码随机盐的字符串 */
    public static final String BASE_STR = "0123456789abcdefghijklmnopqrstuvwxyz~!@#$%^&*()-+";

    /**
     * int 常量 0
     */
    public static final Integer INT_STATE_0 = 0;
    /**
     * int 常量 1
     */
    public static final Integer INT_STATE_1 = 1;
    /**
     * int 常量 2
     */
    public static final Integer INT_STATE_2 = 2;
    /**
     * int 常量 3
     */
    public static final Integer INT_STATE_3 = 3;
    /**
     * int 常量 4
     */
    public static final Integer INT_STATE_4 = 4;
    /**
     * int 常量 5
     */
    public static final Integer INT_STATE_5 = 5;
    /**
     * int 常量 6
     */
    public static final Integer INT_STATE_6 = 6;
    /**
     * int 常量 7
     */
    public static final Integer INT_STATE_7 = 7;
    /**
     * int 常量 8
     */
    public static final Integer INT_STATE_8 = 8;
    /**
     * int 常量 9
     */
    public static final Integer INT_STATE_9 = 9;
    /**
     * int 常量 10
     */
    public static final Integer INT_STATE_10 = 10;

}
