package net.lesscoding.common;


/**
 * @author eleven
 * @date  2022-11-10 19:55:27
 * @description 系统常量类
 * Generated By: lesscoding.net basic service
 * Link to: <a href="https://lesscoding.net">https://lesscoding.net</a>
 * mail to:2496290990@qq.com zjh292411@gmail.com admin@lesscoding.net
 */
public class Consts {
    /** 成功标识 */
    public static final Integer SUCCESS_CODE = 200;
    /** 失败标识 */
    public static final Integer FAILED_CODE = 500;
    /** 成功返回信息 */
    public static final String SUCCESS_MSG = "success";
    /** 失败返回信息 */
    public static final String FAILED_MSG = "failed";

    /** 生成密码随机盐的字符串 */
    public static final String BASE_STR = "0123456789abcdefghijklmnopqrstuvwxyz~!@#$%^&*()-+";

}
